import img1 from '../assets/delicious-vietn.png';
import img2 from '../assets/ramadan-kareem-.png';

const all_orders = [
    {
        id: "0001236",
        date: "1 Nov, 10:20 AM",
        amount: "Php 00.00",
        delivery: "Pick Up",
        timer: "08:00",
        items: [
            {
              name: 'Tabbouleah Salad',
              description: 'Regular Order - no add ons',
              price: '476',
              quantity: '1',
              totalprice: '300',
              image: img1,
            },
            {
              name: 'Baklava',
              description: 'Regular Order - no add ons',
              price: '477',
              quantity: '1',
              totalprice: '300',
              image: img2,
            },
        ],
        totalamount: 776,
    },
    {
        id: "0001235",
        date: "1 Nov, 10:20 AM",
        amount: "Php 00.00",
        delivery: "Pick Up",
        timer: "08:00",
        items: [
            {
              name: 'Tabbouleah Salad',
              description: 'Regular Order - no add ons',
              price: '476',
              quantity: '1',
              totalprice: '300',
              image: img1,
            },
            {
              name: 'Baklava',
              description: 'Regular Order - no add ons',
              price: '477',
              quantity: '1',
              totalprice: '300',
              image: img2,
            },
        ],
        totalamount: 776,
    },
    {
        id: "0001234",
        date: "1 Nov, 10:20 AM",
        amount: "Php 00.00",
        delivery: "Pick Up",
        timer: "08:00",
        items: [
            {
              name: 'Tabbouleah Salad',
              description: 'Regular Order - no add ons',
              price: '476',
              quantity: '1',
              totalprice: '300',
              image: img1,
            },
            {
              name: 'Baklava',
              description: 'Regular Order - no add ons',
              price: '477',
              quantity: '1',
              totalprice: '300',
              image: img2,
            },
        ],
        totalamount: 776,
    },
    {
        id: "0001233",
        date: "1 Nov, 10:20 AM",
        amount: "Php 00.00",
        delivery: "Pick Up",
        timer: "08:00",
        items: [
            {
              name: 'Tabbouleah Salad',
              description: 'Regular Order - no add ons',
              price: '476',
              quantity: '1',
              totalprice: '300',
              image: img1,
            },
            {
              name: 'Baklava',
              description: 'Regular Order - no add ons',
              price: '477',
              quantity: '1',
              totalprice: '300',
              image: img2,
            },
        ],
        totalamount: 776,
    },
    {
        id: "0001232",
        date: "1 Nov, 10:20 AM",
        amount: "Php 00.00",
        delivery: "Pick Up",
        timer: "08:00",
        items: [
            {
              name: 'Tabbouleah Salad',
              description: 'Regular Order - no add ons',
              price: '476',
              quantity: '1',
              totalprice: '300',
              image: img1,
            },
            {
              name: 'Baklava',
              description: 'Regular Order - no add ons',
              price: '477',
              quantity: '1',
              totalprice: '300',
              image: img2,
            },
        ],
        totalamount: 776,
    },
    {
        id: "0001231",
        date: "1 Nov, 10:20 AM",
        amount: "Php 00.00",
        delivery: "Pick Up",
        timer: "08:00",
        items: [
            {
              name: 'Tabbouleah Salad',
              description: 'Regular Order - no add ons',
              price: '476',
              quantity: '1',
              totalprice: '300',
              image: img1,
            },
            {
              name: 'Baklava',
              description: 'Regular Order - no add ons',
              price: '477',
              quantity: '1',
              totalprice: '300',
              image: img2,
            },
        ],
        totalamount: 776,
    },
    {
        id: "0001236",
        date: "1 Nov, 10:20 AM",
        amount: "Php 00.00",
        delivery: "Pick Up",
        timer: "08:00",
        items: [
            {
              name: 'Tabbouleah Salad',
              description: 'Regular Order - no add ons',
              price: '476',
              quantity: '1',
              totalprice: '300',
              image: img1,
            },
            {
              name: 'Baklava',
              description: 'Regular Order - no add ons',
              price: '477',
              quantity: '1',
              totalprice: '300',
              image: img2,
            },
        ],
        totalamount: 776,
    },
    {
        id: "0001235",
        date: "1 Nov, 10:20 AM",
        amount: "Php 00.00",
        delivery: "Pick Up",
        timer: "08:00",
        items: [
            {
              name: 'Tabbouleah Salad',
              description: 'Regular Order - no add ons',
              price: '476',
              quantity: '1',
              totalprice: '300',
              image: img1,
            },
            {
              name: 'Baklava',
              description: 'Regular Order - no add ons',
              price: '477',
              quantity: '1',
              totalprice: '300',
              image: img2,
            },
        ],
        totalamount: 776,
    },
    {
        id: "1234",
        date: "1 Nov, 10:20 AM",
        amount: "Php 00.00",
        delivery: "Pick Up",
        timer: "08:00",
        items: [
            {
              name: 'Tabbouleah Salad',
              description: 'Regular Order - no add ons',
              price: '476',
              quantity: '1',
              totalprice: '300',
              image: img1,
            },
            {
              name: 'Baklava',
              description: 'Regular Order - no add ons',
              price: '477',
              quantity: '1',
              totalprice: '300',
              image: img2,
            },
        ],
        totalamount: 776,

    },
    {
        id: "1233",
        date: "1 Nov, 10:20 AM",
        amount: "Php 00.00",
        delivery: "Pick Up",
        timer: "08:00",
        items: [
            {
              name: 'Tabbouleah Salad',
              description: 'Regular Order - no add ons',
              price: '476',
              quantity: '1',
              totalprice: '300',
              image: img1,
            },
            {
              name: 'Baklava',
              description: 'Regular Order - no add ons',
              price: '477',
              quantity: '1',
              totalprice: '300',
              image: img2,
            },
        ],
        totalamount: 776,
    },
    {
        id: "1232",
        date: "1 Nov, 10:20 AM",
        amount: "Php 00.00",
        delivery: "Pick Up",
        timer: "08:00",
        items: [
            {
              name: 'Tabbouleah Salad',
              description: 'Regular Order - no add ons',
              price: '476',
              quantity: '1',
              totalprice: '300',
              image: img1,
            },
            {
              name: 'Baklava',
              description: 'Regular Order - no add ons',
              price: '477',
              quantity: '1',
              totalprice: '300',
              image: img2,
            },
        ],
        totalamount: 776,
    },
    {
        id: "1231",
        date: "1 Nov, 10:20 AM",
        amount: "Php 00.00",
        delivery: "Pick Up",
        timer: "08:00",
        items: [
            {
              name: 'Tabbouleah Salad',
              description: 'Regular Order - no add ons',
              price: '476',
              quantity: '1',
              totalprice: '300',
              image: img1,
            },
            {
              name: 'Baklava',
              description: 'Regular Order - no add ons',
              price: '477',
              quantity: '1',
              totalprice: '300',
              image: img2,
            },
        ],
        totalamount: 776,
    }
]

export default all_orders;
